<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.goodprice</groupId>
    <artifactId>checkout-cr0</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>6.1.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>${project.basedir}</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <testIncludes>
                        <testInclude>StoreCR0Tests.java</testInclude>
                        <testInclude>AruhazCR0Tesztek.java</testInclude>
                        <testInclude>StoreCR1Tests.java</testInclude>
                        <testInclude>AruhazCR1Tesztek.java</testInclude>
                    </testIncludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.4</version>
                <configuration>
                    <includes>
                        <include>StoreCR0Tests.java</include>
                        <include>AruhazCR0Tesztek.java</include>
                        <include>StoreCR1Tests.java</include>
                        <include>AruhazCR1Tesztek.java</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
